/*
 * This file was automatically generated by EvoSuite
 * Fri Jan 24 15:47:35 GMT 2020
 */

package com.mycompany.app;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mycompany.app.App;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class App_ESTest extends App_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = App.classifyTriangle(2549, 2697, 2549);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = App.classifyTriangle((-1323), 0, (-1930));
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      App app0 = new App();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = App.classifyTriangle(0, 0, 0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      int int0 = App.classifyTriangle(2697, 1740, 2360);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      App.main((String[]) null);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = App.classifyTriangle(1016, 1016, 252);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      int int0 = App.classifyTriangle(996, 996, 996);
      assertEquals(2, int0);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      int int0 = App.classifyTriangle(1955, 3, 2549);
      assertEquals(0, int0);
  }
}
