/*
 * This file was automatically generated by EvoSuite
 * Fri Mar 13 18:51:49 GMT 2020
 */

package com.mycompany.app;

import org.junit.Test;
import static org.junit.Assert.*;
import com.mycompany.app.App;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class App_ESTest_SAMPLED extends App_ESTest_scaffolding {

/*  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      int int0 = App.classifyTriangle(1478, 0, (-1));
      assertEquals(0, int0);
  }

*/  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      int int0 = App.classifyTriangle(3, 606, 606);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      int int0 = App.classifyTriangle(2038, 2042, 1373);
      assertEquals(1, int0);
  }

/*  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      int int0 = App.classifyTriangle(1258, 1258, 2166);
      assertEquals(3, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[3];
      App.main(stringArray0);
      assertEquals(3, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      App app0 = new App();
      assertNotNull(app0);
  }

*/  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      int int0 = App.classifyTriangle(1796, 1796, 1796);
      assertEquals(2, int0);
  }
}
