/*
 * This file was automatically generated by EvoSuite
 * Sun May 03 07:05:09 GMT 2020
 */

package locogp;

import org.junit.Test;
import static org.junit.Assert.*;
import locogp.SortSelection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SortSelection_ESTest_SAMPLED extends SortSelection_ESTest_scaffolding {

/*  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SortSelection sortSelection0 = new SortSelection();
      assertNotNull(sortSelection0);
  }

*/  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer[] integerArray0 = new Integer[8];
      Integer integer0 = new Integer(1114);
      assertNotNull(integer0);
      assertEquals(1114, (int)integer0);
      
      integerArray0[0] = integer0;
      integerArray0[1] = integer0;
      integerArray0[2] = integerArray0[0];
      integerArray0[3] = integer0;
      int int0 = 5;
      integerArray0[4] = integerArray0[2];
      Integer integer1 = new Integer(int0);
      assertTrue(integer1.equals((Object)int0));
      assertFalse(integer1.equals((Object)integer0));
      assertNotNull(integer1);
      assertEquals(5, (int)integer1);
      
      Integer[] integerArray1 = SortSelection.sort(integerArray0, integer1);
      assertTrue(integer1.equals((Object)int0));
      assertFalse(integer1.equals((Object)integer0));
      assertNotNull(integerArray1);
      assertSame(integerArray0, integerArray1);
      assertSame(integerArray1, integerArray0);
      assertEquals(8, integerArray0.length);
      assertEquals(8, integerArray1.length);
  }
}
