/*
 * This file was automatically generated by EvoSuite
 * Sun May 03 14:57:48 GMT 2020
 */

package locogp;

import org.junit.Test;
import static org.junit.Assert.*;
import locogp.SortSelection2;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SortSelection2_ESTest extends SortSelection2_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer[] integerArray0 = new Integer[9];
      Integer integer0 = new Integer(0);
      assertNotNull(integer0);
      assertEquals(0, (int)integer0);
      
      integerArray0[5] = integer0;
      Integer[] integerArray1 = SortSelection2.sort(integerArray0, integerArray0[5]);
      assertSame(integerArray0, integerArray1);
      assertSame(integerArray1, integerArray0);
      assertEquals(9, integerArray0.length);
      assertEquals(9, integerArray1.length);
      assertNotNull(integerArray1);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer[] integerArray0 = new Integer[9];
      Integer integer0 = new Integer(0);
      assertNotNull(integer0);
      assertEquals(0, (int)integer0);
      
      integerArray0[0] = integer0;
      integerArray0[1] = integerArray0[0];
      Integer integer1 = new Integer(552);
      assertFalse(integer1.equals((Object)integer0));
      assertNotNull(integer1);
      assertEquals(552, (int)integer1);
      
      integerArray0[2] = integer1;
      integerArray0[3] = integerArray0[0];
      integerArray0[4] = integerArray0[2];
      integerArray0[5] = integerArray0[2];
      Integer integer2 = new Integer(6);
      assertFalse(integer2.equals((Object)integer0));
      assertFalse(integer2.equals((Object)integer1));
      assertNotNull(integer2);
      assertEquals(6, (int)integer2);
      
      Integer[] integerArray1 = SortSelection2.sort(integerArray0, integer2);
      assertSame(integerArray0, integerArray1);
      assertSame(integerArray1, integerArray0);
      assertFalse(integer2.equals((Object)integer0));
      assertFalse(integer2.equals((Object)integer1));
      assertEquals(9, integerArray0.length);
      assertEquals(9, integerArray1.length);
      assertNotNull(integerArray1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SortSelection2 sortSelection2_0 = new SortSelection2();
      assertNotNull(sortSelection2_0);
  }
}
