/*
 * This file was automatically generated by EvoSuite
 * Wed Apr 22 07:32:22 GMT 2020
 */

package locogp;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import locogp.SortHeap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SortHeap_ESTest_SAMPLED extends SortHeap_ESTest_scaffolding {

/*  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SortHeap sortHeap0 = new SortHeap();
      assertNotNull(sortHeap0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer[] integerArray0 = new Integer[0];
      Integer integer0 = new Integer(3232);
      assertNotNull(integer0);
      assertEquals(3232, (int)integer0);
      
      // Undeclared exception!
      try { 
        SortHeap.sort(integerArray0, integer0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 1615
         //
         verifyException("locogp.SortHeap", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Integer[] integerArray0 = new Integer[8];
      int int0 = 0;
      Integer integer0 = new Integer(0);
      assertNotNull(integer0);
      assertEquals(0, (int)integer0);
      assertTrue(integer0.equals((Object)int0));
      
      integerArray0[0] = integer0;
      integerArray0[2] = (Integer) int0;
      Integer integer1 = Integer.getInteger("locogp.SortHeap", 3);
      assertNotNull(integer1);
      assertEquals(3, (int)integer1);
      assertFalse(integer1.equals((Object)integer0));
      assertFalse(integer1.equals((Object)int0));
      
      integerArray0[1] = integerArray0[0];
      Integer[] integerArray1 = SortHeap.sort(integerArray0, integer1);
      assertEquals(8, integerArray0.length);
      assertEquals(8, integerArray1.length);
      assertNotNull(integerArray1);
      assertFalse(integer1.equals((Object)integer0));
      assertFalse(integer1.equals((Object)int0));
      assertSame(integerArray0, integerArray1);
      assertSame(integerArray1, integerArray0);
  }

*/  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Integer[] integerArray0 = new Integer[8];
      int int0 = 0;
      Integer integer0 = new Integer(0);
      assertNotNull(integer0);
      assertEquals(0, (int)integer0);
      assertTrue(integer0.equals((Object)int0));
      
      integerArray0[0] = integer0;
      integerArray0[2] = (Integer) int0;
      int int1 = 3;
      Integer integer1 = Integer.getInteger("locogp.SortHeap", 3);
      assertNotNull(integer1);
      assertEquals(3, (int)integer1);
      assertFalse(integer1.equals((Object)int0));
      assertFalse(integer1.equals((Object)integer0));
      
      integerArray0[1] = (Integer) int1;
      Integer[] integerArray1 = SortHeap.sort(integerArray0, integer1);
      assertEquals(8, integerArray0.length);
      assertEquals(8, integerArray1.length);
      assertNotNull(integerArray1);
      assertFalse(integer1.equals((Object)int0));
      assertFalse(integer1.equals((Object)integer0));
      assertSame(integerArray0, integerArray1);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Integer integer0 = new Integer(0);
      assertNotNull(integer0);
      assertEquals(0, (int)integer0);
      
      int int0 = 3;
      Integer integer1 = new Integer((-88));
      assertNotNull(integer1);
      assertEquals((-88), (int)integer1);
      assertFalse(integer1.equals((Object)integer0));
      assertFalse(integer1.equals((Object)int0));
      
      Integer[] integerArray0 = new Integer[3];
      integerArray0[0] = integer0;
      integerArray0[1] = integer0;
      integerArray0[2] = integer1;
      Integer[] integerArray1 = SortHeap.sort(integerArray0, (Integer) int0);
      assertEquals(3, integerArray0.length);
      assertEquals(3, integerArray1.length);
      assertNotNull(integerArray1);
      assertSame(integerArray0, integerArray1);
      assertSame(integerArray1, integerArray0);
  }
}
