/*
 * This file was automatically generated by EvoSuite
 * Sun May 03 07:36:46 GMT 2020
 */

package locogp;

import org.junit.Test;
import static org.junit.Assert.*;
import locogp.SortSelection;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, useJEE = true) 
public class SortSelection_ESTest extends SortSelection_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer[] integerArray0 = new Integer[0];
      Integer integer0 = new Integer(0);
      assertNotNull(integer0);
      assertEquals(0, (int)integer0);
      
      Integer[] integerArray1 = SortSelection.sort(integerArray0, integer0);
      assertNotNull(integerArray1);
      assertEquals(0, integerArray0.length);
      assertEquals(0, integerArray1.length);
      assertSame(integerArray0, integerArray1);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Integer integer0 = new Integer(1637);
      assertNotNull(integer0);
      assertEquals(1637, (int)integer0);
      
      Integer integer1 = new Integer(7);
      assertNotNull(integer1);
      assertFalse(integer1.equals((Object)integer0));
      assertEquals(7, (int)integer1);
      
      Integer[] integerArray0 = new Integer[8];
      integerArray0[0] = integer1;
      integerArray0[1] = integer0;
      integerArray0[2] = integer1;
      integerArray0[3] = integer0;
      integerArray0[4] = integerArray0[0];
      integerArray0[5] = integer1;
      integerArray0[6] = integer1;
      Integer[] integerArray1 = SortSelection.sort(integerArray0, integerArray0[2]);
      assertNotNull(integerArray1);
      assertEquals(8, integerArray0.length);
      assertEquals(8, integerArray1.length);
      assertSame(integerArray0, integerArray1);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      SortSelection sortSelection0 = new SortSelection();
      assertNotNull(sortSelection0);
  }
}
